// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyszHGmTS0KxfqFHkcAhI-EqvgzVb6sR4',
    appId: '1:305055391712:web:f55f3e33fa1df523131585',
    messagingSenderId: '305055391712',
    projectId: 'andw-31872',
    authDomain: 'andw-31872.firebaseapp.com',
    storageBucket: 'andw-31872.firebasestorage.app',
    measurementId: 'G-3VRYYF92V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtvpwjfyelWtibpRdijAl76ckKLC9scdM',
    appId: '1:305055391712:android:c83c51b08c761985131585',
    messagingSenderId: '305055391712',
    projectId: 'andw-31872',
    storageBucket: 'andw-31872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqlSpiRlsP5MDcboEywtwY9nkQFHA9h5A',
    appId: '1:305055391712:ios:09e434f5bbf96b8d131585',
    messagingSenderId: '305055391712',
    projectId: 'andw-31872',
    storageBucket: 'andw-31872.firebasestorage.app',
    iosBundleId: 'com.example.aAndw',
  );
}
