// Mocks generated by Mockito 5.4.6 from annotations
// in a_and_w/test/features/pengantaran/domain/repository/pengantaran_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:a_and_w/features/pengantaran/data/datasource/pengantaran_remote_datasource.dart'
    as _i5;
import 'package:a_and_w/features/pengantaran/data/model/distrik_response.dart'
    as _i4;
import 'package:a_and_w/features/pengantaran/data/model/kota_response.dart'
    as _i3;
import 'package:a_and_w/features/pengantaran/data/model/provinsi_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProvinsiResponse_0 extends _i1.SmartFake
    implements _i2.ProvinsiResponse {
  _FakeProvinsiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKotaResponse_1 extends _i1.SmartFake implements _i3.KotaResponse {
  _FakeKotaResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDistrikResponse_2 extends _i1.SmartFake
    implements _i4.DistrikResponse {
  _FakeDistrikResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PengantaranRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPengantaranRemoteDatasource extends _i1.Mock
    implements _i5.PengantaranRemoteDatasource {
  MockPengantaranRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ProvinsiResponse> getProvinsi() =>
      (super.noSuchMethod(
            Invocation.method(#getProvinsi, []),
            returnValue: _i6.Future<_i2.ProvinsiResponse>.value(
              _FakeProvinsiResponse_0(
                this,
                Invocation.method(#getProvinsi, []),
              ),
            ),
          )
          as _i6.Future<_i2.ProvinsiResponse>);

  @override
  _i6.Future<_i3.KotaResponse> getKota(String? provinsiId) =>
      (super.noSuchMethod(
            Invocation.method(#getKota, [provinsiId]),
            returnValue: _i6.Future<_i3.KotaResponse>.value(
              _FakeKotaResponse_1(
                this,
                Invocation.method(#getKota, [provinsiId]),
              ),
            ),
          )
          as _i6.Future<_i3.KotaResponse>);

  @override
  _i6.Future<_i4.DistrikResponse> getDistrik(String? kotaId) =>
      (super.noSuchMethod(
            Invocation.method(#getDistrik, [kotaId]),
            returnValue: _i6.Future<_i4.DistrikResponse>.value(
              _FakeDistrikResponse_2(
                this,
                Invocation.method(#getDistrik, [kotaId]),
              ),
            ),
          )
          as _i6.Future<_i4.DistrikResponse>);
}
