// Mocks generated by Mockito 5.4.6 from annotations
// in a_and_w/test/features/pengantaran/presentation/bloc/pengantaran_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:a_and_w/core/exceptions/exceptions.dart' as _i6;
import 'package:a_and_w/features/pengantaran/domain/entities/data_wilayah_entity.dart'
    as _i7;
import 'package:a_and_w/features/pengantaran/domain/repository/pengantaran_repository.dart'
    as _i2;
import 'package:a_and_w/features/pengantaran/domain/usecase/get_list_distrik.dart'
    as _i4;
import 'package:a_and_w/features/pengantaran/domain/usecase/get_list_kota.dart'
    as _i9;
import 'package:a_and_w/features/pengantaran/domain/usecase/get_list_provinsi.dart'
    as _i8;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePengantaranRepository_0 extends _i1.SmartFake
    implements _i2.PengantaranRepository {
  _FakePengantaranRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetListDistrik].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListDistrik extends _i1.Mock implements _i4.GetListDistrik {
  MockGetListDistrik() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PengantaranRepository get pengantaranRepository =>
      (super.noSuchMethod(
            Invocation.getter(#pengantaranRepository),
            returnValue: _FakePengantaranRepository_0(
              this,
              Invocation.getter(#pengantaranRepository),
            ),
          )
          as _i2.PengantaranRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>> call(
    String? idKota,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [idKota]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.DataWilayahEntity>>(
                    this,
                    Invocation.method(#call, [idKota]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>>);
}

/// A class which mocks [GetListProvinsi].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListProvinsi extends _i1.Mock implements _i8.GetListProvinsi {
  MockGetListProvinsi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PengantaranRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePengantaranRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PengantaranRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.DataWilayahEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>>);
}

/// A class which mocks [GetListKota].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListKota extends _i1.Mock implements _i9.GetListKota {
  MockGetListKota() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PengantaranRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePengantaranRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PengantaranRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>> call(
    String? provinsiId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [provinsiId]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.DataWilayahEntity>>(
                    this,
                    Invocation.method(#call, [provinsiId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.DataWilayahEntity>>>);
}
